### ISSUE TITLE
Weird wobbling artifacts in immersive mode on Vision Pro

### ISSUE THREAD

**Issue by JiamingSuen** [scier/MetalSplatter#12]
I noticed this strange wobbling artifact (especially on the depth edges) on Vision Pro. The same issue can be reproduced with a smaller splat file (34K points) and the closed-sourced version of the app on the App Store. I'm on visionOS v1.1.2.

https://github.com/scier/MetalSplatter/assets/8616975/16529d0e-abd7-4267-8964-98234464f43e

https://github.com/scier/MetalSplatter/assets/8616975/d5532caa-a25b-48c8-b540-b7241a3867fd

Hope this can be easily fixed. Thanks for this amazing repo!

**Comment by scier** [comment]
What you're seeing -- which I've dubbed WobbleSplat, trademark pending -- is a combination of two things. First, the Vision Pro extrapolates missed frames by reprojecting previous frames, using those frames' depth to warp the textures. VP needs to render at 90fps, so if the splat is rendering at anything less than that, it'll miss a frame which is super-ugly and disorienting in VR, so the VP creates a new one to match the user's latest pose. Reprojection isn't perfect -- especially around depth discontinuities, i.e. edges of foreground objects -- but it depends on having good depth to work at all.

Which brings us to the second issue: rendering depth is hard with splats (because of the transparency and layers involved). For instance, if there's a large, nearly-invisible splat, the depth buffer will still show that "ghost bubble" as the closest object for those pixels, and so the reprojection will happily warp the pixels as though they're closer to you than they actually are, and you'll see a warped bubble.

The faster you move, the bigger (i.e. slower to render) the splat model, and the more noisy large translucent splats there are in the model, the more this will all stand out.

If you want to see what things look like with no reprojection at all -- well, that's hard, it's automatic. But if you want to turn it off "halfway", you can turn off depth: in SplatRenderer, set depthStateDescriptor.isDepthWriteEnabled = false. Then the depth buffer will contain entirely 1.0. The reprojection will then treat everything as though it's really far away. Which means it does *just fine* when you just turn your head in place, but if you move side-to-side, it can't compensate, so foreground objects jitter a lot and seem to "lag" (since they can't be moved to the "right" place).

There are a few ways to fix this, none easy (sorry):
* Render at 90fps. If you can improve the efficiency of the renderer enough to do that, I'll be quite happy. You'll notice the WobbleSplat effect is more pronounced on bigger splats; this is why.
* Have very clean models with no translucent "floaters", or smaller models with fewer/smaller splats. This helps a *lot*, but it's perfect; you'll still see wobbles around depth discontinuities (foreground edges) and truly transparent areas.
* Write better depth values; e.g. write depth as an alpha-blended composite, similar to colors. This may be feasible, but so far Metal has defeated every attempt I've made to do it efficiently. Again, I'd love to see a patch that did this (well)! Although it still wouldn't be perfect (see the previous bullet)

**Comment by JiamingSuen** [comment]
Thanks for your detailed reply! Now I believe I've fully understood the problem. However, I didn't find the same issue with the WebXR mode in https://github.com/mkkellogg/GaussianSplats3D (although it could be very laggy with large splat files). I'll try to dig deeper to figure out why.

**Comment by jerbeers** [comment]
I don't know if this is the same thing, but it looks like the interpolated frames are tracking with head movement too. I don't see the same thing in the MetalSplatter app on the store. If I run in the debugger, I get a system message that content will be head anchored while debugging. Other than the system message, it looks the same if I run it directly. This is on a fairly large model, but the store app renders it without the jitter movement.

![Frame-11-05-2024-04-37-22](https://github.com/scier/MetalSplatter/assets/276773/776044d0-ec1b-4ccf-8d36-0706e3cd3413)

**Comment by scier** [comment]
@jerbeers are you perchance running with the debugger attached (and/or with a Debug build) when you see the increased jitter? The debugger causes the app to render a lot more slowly in my experience.

**Comment by jerbeers** [comment]
I've tried with the debugger attached and without it, but both are debug builds. I haven't tried a release build.

**Comment by jerbeers** [comment]
I take it back, it looks like the scheme is configured to run a release build.
