### ISSUE TITLE
how to pan/rotate splat？

### ISSUE THREAD

**Issue by zxwzxw** [scier/MetalSplatter#13]
”The camera controls are significantly easier to use now: you use two pinches consistently, a lot like 2D multitouch pan/rotate except in 3D“   how to pan/rotate splat？

**Comment by scier** [comment]
This library does not have any camera controls or user interaction; that's just in the App Store app, which is not part of this repo, which is just the renderer and a minimally-interactive sample app (but there's really nothing special in the App Store app, I just didn't bother to clean it up and release it as OSS since I figure it's much less useful to folks than the renderer). You'll need to pair this renderer with your own camera controls and other app logic (or use frameworks from elsewhere). It just uses standard view/projection matrices.

In the app, panning and rotating are done by pinching with both hands simultaneously.
