### ISSUE TITLE
How do I switch to mixed mode

### ISSUE THREAD

**Issue by zxwzxw** [scier/MetalSplatter#15]
"How do I switch to mixed mode? Why, after using the code .immersionStyle(selection: .constant(.mixed), in: .mixed), is the background still black when I launch Splat, and I don't see the real environment?"

**Comment by scier** [comment]
Unfortunately this is an explicit limitation in visionOS: Metal content can only be renderer in full immersion. This is because of the security model, which does most rendering (via RealityKit) out of process and then also composites with the video feed out-of-process, whereas Metal rendering occurs in-process.

It's possible this could be changed in a future release of visionOS (either by allowing Metal content to be composited out-of-process after rendering, or by loosening the security model); but for now, Apple considers it a feature, not a bug.

See https://developer.apple.com/videos/play/wwdc2023/10089

**Comment by Yang-Xijie** [comment]
related issue: https://github.com/scier/MetalSplatter/issues/4

**Comment by sam598** [comment]
VisonOS 2 now supports metal rendering in mixed immersion mode. Would be great to see it added.
https://github.com/scier/MetalSplatter/issues/18
