### ISSUE TITLE
Compilation error on macOS with Apple Silicon

### ISSUE THREAD

**Issue by JiamingSuen** [scier/MetalSplatter#3]
Error message:
```
MetalSplatter/MetalSplatter/Sources/SplatRenderer.swift:69:16 'Float16' is unavailable in macOS
```

https://github.com/scier/MetalSplatter/blob/221348301cae5e14388410b9ed080c3d61cbfbbc/MetalSplatter/Sources/SplatRenderer.swift#L68-L79

I'm on M1 Max with macOS 14.2.1. 
According to [this thread](https://forums.swift.org/t/add-float16/19370), it seems to be a missing feature for macOS. It works fine for my iPhone and visionOS simulator. 

Will there be an easy fix? Development will be faster if the code can be compiled natively on a Mac.

Thanks for this amazing repo!

**Comment by Zhangyangrui916** [comment]
应该是Xcode的bug
https://github.com/Zhangyangrui916/MetalSplatter/commit/c09ab6015439a7e76f2f17a5a481e8b6908df79d

**Comment by scier** [comment]
The root cause is that Xcode stubbornly insists on building Swift Packages as universal binaries, even if your app is only supporting Apple Silicon. However, while Float16 is supported on arm64 on macOS, it is *not* supported on x86_64. So for now I've pushed a kludgy workaround: build successfully on x86_64 (with a warning) but fail at runtime. Not pretty and if you're supporting Intel you're gonna crash when instantiating SplatRenderer.

It *might* be possible to send a preprocessor directive to the shader compiler to expect Float, but it might require some manual build settings for apps, and would be much less memory-efficient on Intel; and I can't imagine this would run at all acceptably on Intel anyway. If somebody really needs that, please open a separate ticket for it.

For now, this workaround should fix the build on Apple Silicon macOS.
